### ISSUE TITLE
FXConverter example is unstable

### ISSUE THREAD

**Issue by ryan-collingham** [Morgan-Stanley/testplan#169]
FXConverter example has started failing and blocking CI jobs. Looks like the driver is failing to start correctly:

```
While starting resource [converter]
14:43:20 E                 Traceback (most recent call last):
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/common/entity/base.py", line 143, in start(
14:43:20 E                         Environment[[('server', <testplan.testing.multitest.driver.tcp.server.TCPServer object at 0x2b73c5c6e590>), ('con...)
14:43:20 E                     resource.wait(resource.STATUS.STARTED)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/common/entity/base.py", line 435, in wait(<driver.FXConverter object at 0x2b73c5c6e8d0>, 'STARTED', 3600)
14:43:20 E                     self._wait_handlers[target_status](timeout=timeout)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/testing/multitest/driver/base.py", line 170, in _wait_started(<driver.FXConverter object at 0x2b73c5c6e8d0>, 3600)
14:43:20 E                     self.started_check(timeout=timeout)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/examples/App/FXConverter/driver.py", line 25, in started_check(<driver.FXConverter object at 0x2b73c5c6e8d0>, 3600)
14:43:20 E                     super(FXConverter, self).started_check(timeout=timeout)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/testing/multitest/driver/base.py", line 152, in started_check(<driver.FXConverter object at 0x2b73c5c6e8d0>, 3600)
14:43:20 E                     raise_on_timeout=True)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/common/utils/timing.py", line 150, in wait(<function <lambda> at 0x2b73c5c990c8>, 60, 0.05, True)
14:43:20 E                     raise TimeoutException(msg)
14:43:20 E                 TimeoutException: Timeout after 60 seconds.
14:43:20 E                 Timed out starting FXConverter(converter): unmatched log_regexps in /var/tmp/pjenkbld/testplan/fxconverter/TestFXConverter/converter/stdout.
14:43:20 E                  log_regexps matched: []
14:43:20 E                 Unmatched: ["REGEX('Converter started.')", "REGEX('.*Listener on: (?P<listen_address>.*)')"]
14:43:20 E                 While starting resource [converter]
14:43:20 E                 Traceback (most recent call last):
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/common/entity/base.py", line 143, in start(
14:43:20 E                         Environment[[('server', <testplan.testing.multitest.driver.tcp.server.TCPServer object at 0x2b73c5c6e590>), ('con...)
14:43:20 E                     resource.wait(resource.STATUS.STARTED)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/common/entity/base.py", line 435, in wait(<driver.FXConverter object at 0x2b73c5c6e8d0>, 'STARTED', 3600)
14:43:20 E                     self._wait_handlers[target_status](timeout=timeout)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/testing/multitest/driver/base.py", line 170, in _wait_started(<driver.FXConverter object at 0x2b73c5c6e8d0>, 3600)
14:43:20 E                     self.started_check(timeout=timeout)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/examples/App/FXConverter/driver.py", line 25, in started_check(<driver.FXConverter object at 0x2b73c5c6e8d0>, 3600)
14:43:20 E                     super(FXConverter, self).started_check(timeout=timeout)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/testing/multitest/driver/base.py", line 152, in started_check(<driver.FXConverter object at 0x2b73c5c6e8d0>, 3600)
14:43:20 E                     raise_on_timeout=True)
14:43:20 E                   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-continuous-rhel6-python-2.7.9/ets/testplan/testplan/src/oss/testplan/common/utils/timing.py", line 150, in wait(<function <lambda> at 0x2b73c5c990c8>, 60, 0.05, True)
14:43:20 E                     raise TimeoutException(msg)
14:43:20 E                 TimeoutException: Timeout after 60 seconds.
14:43:20 E                 Timed out starting FXConverter(converter): unmatched log_regexps in /var/tmp/pjenkbld/testplan/fxconverter/TestFXConverter/converter/stdout.
14:43:20 E                  log_regexps matched: []
14:43:20 E                 Unmatched: ["REGEX('Converter started.')", "REGEX('.*Listener on: (?P<listen_address>.*)')"]
```

**Comment by ryan-collingham** [comment]
Haven't seen this reoccur for a while, closing.
