### ISSUE TITLE
Interactive reload test is unstable

### ISSUE THREAD

**Issue by ryan-collingham** [Morgan-Stanley/testplan#174]
The interactive mode reload test is currently unstable and has been disabled. The following traceback is seen:

```
14:03:58 Traceback (most recent call last):
14:03:58   File "interactive_executable.py", line 67, in <module>
14:03:58     plan.i.reload()
14:03:58   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-custom-rhel6-python-3.4.2/ets/testplan/testplan/src/lib/testplan/oss/runnable/interactive/base.py", line 489, in reload
14:03:58     self._reloader.reload(tests, rebuild_dependencies=rebuild_dependencies)
14:03:58   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-custom-rhel6-python-3.4.2/ets/testplan/testplan/src/lib/testplan/oss/runnable/interactive/reloader.py", line 219, in reload
14:03:58     self._reload_deps(filepath, reloaded, suite_dict)
14:03:58   File "/var/tmp/pjenkslv/jenkins/workspace/ets-testplan-custom-rhel6-python-3.4.2/ets/testplan/testplan/src/lib/testplan/oss/runnable/interactive/reloader.py", line 194, in _reload_deps
14:03:58     reload_module(to_reload)
14:03:58   File "/ms/dist/python/PROJ/core/3.4.4/exec/lib/python3.4/importlib/__init__.py", line 149, in reload
14:03:58     methods.exec(module)
14:03:58   File "<frozen importlib._bootstrap>", line 1134, in exec
14:03:58 AttributeError: 'NoneType' object has no attribute 'name'
```

So far this has only been seen when running with python 3, but the test has been disabled entirely until we understand why it is failing better.

**Comment by ryan-collingham** [comment]
Reloader has been extensively rewritten and this issue no longer persists.
