### ISSUE TITLE
Interactive example in jupyter notebook is not up-to-date

### ISSUE THREAD

**Issue by francoisverbeek** [Morgan-Stanley/testplan#338]
How to reproduce: clean clone of master; `pip install jupyter lab`; execute the `Basic/test_plan_notebook.ipynb` in the interactive examples directory.  

I suspect due to the recent interactive refactoring the notebook has not been kept up-to-date. The `plan.run()` step doesn't detect interactive mode and instead says 'No tests were run' and `plan.i.test` raises a `AttributeError`.

trying to change `interactive=True` to `interactive_port=8082` for instance then creates another issue with the reload logic:
```Starting TestRunner[MyPlan] in interactive mode
Traceback (most recent call last):
  File "/Users/frans/Documents/GitHub/testplan/testplan/common/entity/base.py", line 860, in run(<testplan.runnable.base.TestRunner object at 0x118d39fd0>)
    target=self, http_port=self.cfg.interactive_port)
  File "/Users/frans/Documents/GitHub/testplan/testplan/runnable/interactive/base.py", line 113, in __init__(
        <testplan.runnable.interactive.base.TestRunnerIHandler object at 0x10a33e828>,
        <testplan.runnable.base.TestRunner object at 0x118d39fd0>,
        10,
        8082)
    self._reloader = ModuleReloader(extra_deps=self.cfg.extra_deps)
  File "/Users/frans/Documents/GitHub/testplan/testplan/runnable/interactive/reloader.py", line 40, in __init__(<testplan.runnable.interactive.reloader.ModuleReloader object at 0x118d39f28>, [])
    self._build_dependencies(extra_deps))
  File "/Users/frans/Documents/GitHub/testplan/testplan/runnable/interactive/reloader.py", line 81, in _build_dependencies(<testplan.runnable.interactive.reloader.ModuleReloader object at 0x118d39f28>, [])
    main_module_file = sys.modules['__main__'].__file__
AttributeError: module '__main__' has no attribute '__file__'
```

**Comment by ryan-collingham** [comment]
Hi Francois,

Yes this is expected, we are refactoring interactive mode and focussing on the web UI first. We removed some older examples that do not work with the new API, we must have missed the Jupyter example.

The web UI for interactive mode will be ready very soon. For use of the interactive mode outside of the UI, please see the API docs - the link to the Swagger UI page is generated for you when you start the interactive mode with `-i` flag. Hopefully this will give you a pointer on how to control the interactive mode over HTTP from Jupyter or any other client.

**Comment by francoisverbeek** [comment]
Fair enough. Thank you for the clarification, looking forward to the new ui!
