### ISSUE TITLE
PyTest runner does not yet work with interactive mode

### ISSUE THREAD

**Issue by ryan-collingham** [Morgan-Stanley/testplan#400]
Expected - PyTest runner needs to implement both dry_run() and run_tests_iter() methods to work with interactive mode.

Current behaviour: running any PyTest instance raises NotImplementedError on the backend.

**Comment by ryan-collingham** [comment]
Traceback:

```
Traceback (most recent call last):
  File "C:\Users\Ryan\Documents\code\testplan\testplan\runnable\interactive\base.py", line 735, in _log_async_exceptions
    future.result()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Ryan\Documents\code\testplan\testplan\runnable\interactive\base.py", line 192, in run_test
    self._merge_testcase_reports(test.run_testcases_iter())
  File "C:\Users\Ryan\Documents\code\testplan\testplan\testing\base.py", line 331, in run_testcases_iter
    raise NotImplementedError
NotImplementedError
```
